package com.qqms.model;

// Generated 2015-6-17 10:26:05 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.alibaba.fastjson.annotation.JSONField;

/**
 * AccountInfo generated by hbm2java
 */
@Entity
@Table(name = "t_bp_account_info")
public class AccountInfo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String accountId;
	private String bankName;
	private String accountName;
	private String accountNum;
	private String cusId;
	private String cusType;
	private Set<LoanorderAndAccountinfo> loanorderAndAccountinfos = new HashSet<LoanorderAndAccountinfo>(0);

	public AccountInfo() {
	}

	public AccountInfo(String accountId) {
		this.accountId = accountId;
	}

	public AccountInfo(String accountId, String bankName,
			String accountName, String accountNum, String cusId,
			String cusType, Set<LoanorderAndAccountinfo> loanorderAndAccountinfos) {
		this.accountId = accountId;
		this.bankName = bankName;
		this.accountName = accountName;
		this.accountNum = accountNum;
		this.cusId = cusId;
		this.cusType = cusType;
		this.loanorderAndAccountinfos = loanorderAndAccountinfos;
	}

	@Id
	@Column(name = "ACCOUNT_ID", unique = true, nullable = false, length = 40)
	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	@Column(name = "BANK_NAME", length = 120)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "ACCOUNT_NAME", length = 120)
	public String getAccountName() {
		return this.accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	@Column(name = "ACCOUNT_NUM", length = 100)
	public String getAccountNum() {
		return this.accountNum;
	}

	public void setAccountNum(String accountNum) {
		this.accountNum = accountNum;
	}

	@Column(name = "CUS_ID", length = 40)
	public String getCusId() {
		return this.cusId;
	}

	public void setCusId(String cusId) {
		this.cusId = cusId;
	}

	@Column(name = "CUS_TYPE", length = 30)
	public String getCusType() {
		return this.cusType;
	}

	public void setCusType(String cusType) {
		this.cusType = cusType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountInfo")
	@JSONField(serialize = false)
	public Set<LoanorderAndAccountinfo> getLoanorderAndAccountinfos() {
		return this.loanorderAndAccountinfos;
	}

	public void setLoanorderAndAccountinfos(Set<LoanorderAndAccountinfo> loanorderAndAccountinfos) {
		this.loanorderAndAccountinfos = loanorderAndAccountinfos;
	}

}
