package com.qqms.model;

// Generated 2015-5-28 15:47:28 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbArea generated by hbm2java
 */
@Entity
@Table(name = "t_area")
public class Area implements java.io.Serializable {

	private Integer areaId;
	private Integer parentId;
	private String areaName;
	private String pyName;
	private Integer zipcode;
	private Boolean areaType;
	private Boolean special;

	public Area() {
	}

	public Area(Integer parentId, String areaName, String pyName,
			Integer zipcode, Boolean areaType, Boolean special) {
		this.parentId = parentId;
		this.areaName = areaName;
		this.pyName = pyName;
		this.zipcode = zipcode;
		this.areaType = areaType;
		this.special = special;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "area_id", unique = true, nullable = false)
	public Integer getAreaId() {
		return this.areaId;
	}

	public void setAreaId(Integer areaId) {
		this.areaId = areaId;
	}

	@Column(name = "parent_id")
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@Column(name = "area_name", length = 50)
	public String getAreaName() {
		return this.areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	@Column(name = "py_name", length = 50)
	public String getPyName() {
		return this.pyName;
	}

	public void setPyName(String pyName) {
		this.pyName = pyName;
	}

	@Column(name = "zipcode")
	public Integer getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(Integer zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "area_type")
	public Boolean getAreaType() {
		return this.areaType;
	}

	public void setAreaType(Boolean areaType) {
		this.areaType = areaType;
	}

	@Column(name = "special")
	public Boolean getSpecial() {
		return this.special;
	}

	public void setSpecial(Boolean special) {
		this.special = special;
	}

}
