package com.qqms.model;

// Generated 2015-6-24 10:29:40 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

import com.alibaba.fastjson.annotation.JSONField;

/**
 * Company generated by hbm2java
 */
@Entity
@Table(name = "t_bp_company")
public class Company implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String comId;
	private String loanerId;
	private String name;
	private String address;
	private String corpNature;
	private String tele;
	private Date foundedTime;
	private Integer areaSize;
	private String businessScope;
	private BigDecimal regCapital;
	private Integer empAmount;
	private Set<LoanorderAndCompany> loanorderAndCompanies = new HashSet<LoanorderAndCompany>(
			0);

	public Company() {
	}

	public Company(String comId) {
		this.comId = comId;
	}

	public Company(String comId, String loanerId, String name, String address,
			String corpNature, String tele, Date foundedTime, Integer areaSize,
			String businessScope, BigDecimal regCapital, Integer empAmount,
			Set<LoanorderAndCompany> loanorderAndCompanies) {
		this.comId = comId;
		this.loanerId = loanerId;
		this.name = name;
		this.address = address;
		this.corpNature = corpNature;
		this.tele = tele;
		this.foundedTime = foundedTime;
		this.areaSize = areaSize;
		this.businessScope = businessScope;
		this.regCapital = regCapital;
		this.empAmount = empAmount;
		this.loanorderAndCompanies = loanorderAndCompanies;
	}

	@Id
	@GenericGenerator(name = "systemUUID", strategy = "uuid")
	@GeneratedValue(generator = "systemUUID")
	@Column(name = "COM_ID", insertable = true, updatable = true, nullable = false, length = 40, unique = true)
	public String getComId() {
		return this.comId;
	}

	public void setComId(String comId) {
		this.comId = comId;
	}

	@Column(name = "LOANER_ID", length = 40)
	public String getLoanerId() {
		return this.loanerId;
	}

	public void setLoanerId(String loanerId) {
		this.loanerId = loanerId;
	}

	@Column(name = "NAME", length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ADDRESS", length = 512)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "CORP_NATURE", length = 100)
	public String getCorpNature() {
		return this.corpNature;
	}

	public void setCorpNature(String corpNature) {
		this.corpNature = corpNature;
	}

	@Column(name = "TELE", length = 32)
	public String getTele() {
		return this.tele;
	}

	public void setTele(String tele) {
		this.tele = tele;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FOUNDED_TIME", length = 10)
	public Date getFoundedTime() {
		return this.foundedTime;
	}

	public void setFoundedTime(Date foundedTime) {
		this.foundedTime = foundedTime;
	}

	@Column(name = "AREA_SIZE")
	public Integer getAreaSize() {
		return this.areaSize;
	}

	public void setAreaSize(Integer areaSize) {
		this.areaSize = areaSize;
	}

	@Column(name = "BUSINESS_SCOPE", length = 200)
	public String getBusinessScope() {
		return this.businessScope;
	}

	public void setBusinessScope(String businessScope) {
		this.businessScope = businessScope;
	}

	@Column(name = "REG_CAPITAL", precision = 20, scale = 5)
	public BigDecimal getRegCapital() {
		return this.regCapital;
	}

	public void setRegCapital(BigDecimal regCapital) {
		this.regCapital = regCapital;
	}

	@Column(name = "EMP_AMOUNT")
	public Integer getEmpAmount() {
		return this.empAmount;
	}

	public void setEmpAmount(Integer empAmount) {
		this.empAmount = empAmount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "company")
	@JSONField(serialize = false)
	public Set<LoanorderAndCompany> getLoanorderAndCompanies() {
		return this.loanorderAndCompanies;
	}

	public void setLoanorderAndCompanies(
			Set<LoanorderAndCompany> loanorderAndCompanies) {
		this.loanorderAndCompanies = loanorderAndCompanies;
	}

}
