package com.qqms.model;

// Generated 2015-6-24 10:29:40 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

import com.alibaba.fastjson.annotation.JSONField;

/**
 * Contacts generated by hbm2java
 */
@Entity
@Table(name = "t_bp_contacts")
public class Contacts implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String contactId;
	private String cusId;
	private String cusType;
	private String contactStatus;
	private String chName;
	private String enName;
	private String genderType;
	private Integer age;
	private String jobTitle;
	private BigDecimal annualSalary;
	private Integer yearsOfWork;
	private String compTel;
	private String compAddr;
	private String currAddr;
	private Date birthday;
	private String idType;
	private String idNo;
	private String tel;
	private String fixedTel;
	private String email;
	private String relationship;
	private String zip;
	private String workplace;
	private String creator;
	private Date createDate;

	/*** 单位地址 ***/
	private Integer compProvince;// 省
	private Integer compCity;// 市
	private Integer compArea;// 县
	private String compAddrDetails;// 详细

	/*** 家庭地址 ***/
	private Integer familyProvince;// 省
	private Integer familyCity;// 市
	private Integer familyArea;// 县
	private String familyAddrDetails;// 详细

	private Set<LoanorderAndContacts> loanorderAndContactses = new HashSet<LoanorderAndContacts>(
			0);

	public Contacts() {
	}

	public Contacts(String contactId) {
		this.contactId = contactId;
	}

	public Contacts(String contactId, String cusId, String cusType,
			String contactStatus, String chName, String enName,
			String genderType, Integer age, String jobTitle,
			BigDecimal annualSalary, Integer yearsOfWork, String compTel,
			String compAddr, String currAddr, Date birthday, String idType,
			String idNo, String tel, String fixedTel, String email,
			String relationship, String zip, String workplace, String creator,
			Date createDate, Set<LoanorderAndContacts> loanorderAndContactses) {
		this.contactId = contactId;
		this.cusId = cusId;
		this.cusType = cusType;
		this.contactStatus = contactStatus;
		this.chName = chName;
		this.enName = enName;
		this.genderType = genderType;
		this.age = age;
		this.jobTitle = jobTitle;
		this.annualSalary = annualSalary;
		this.yearsOfWork = yearsOfWork;
		this.compTel = compTel;
		this.compAddr = compAddr;
		this.currAddr = currAddr;
		this.birthday = birthday;
		this.idType = idType;
		this.idNo = idNo;
		this.tel = tel;
		this.fixedTel = fixedTel;
		this.email = email;
		this.relationship = relationship;
		this.zip = zip;
		this.workplace = workplace;
		this.creator = creator;
		this.createDate = createDate;
		this.loanorderAndContactses = loanorderAndContactses;
	}

	@Id
	@GenericGenerator(name = "systemUUID", strategy = "uuid")
	@GeneratedValue(generator = "systemUUID")
	@Column(name = "CONTACT_ID", insertable = true, updatable = true, nullable = false, length = 40, unique = true)
	public String getContactId() {
		return this.contactId;
	}

	public void setContactId(String contactId) {
		this.contactId = contactId;
	}

	@Column(name = "CUS_ID", length = 40)
	public String getCusId() {
		return this.cusId;
	}

	public void setCusId(String cusId) {
		this.cusId = cusId;
	}

	@Column(name = "CUS_TYPE", length = 30)
	public String getCusType() {
		return this.cusType;
	}

	public void setCusType(String cusType) {
		this.cusType = cusType;
	}

	@Column(name = "CONTACT_STATUS", length = 1)
	public String getContactStatus() {
		return this.contactStatus;
	}

	public void setContactStatus(String contactStatus) {
		this.contactStatus = contactStatus;
	}

	@Column(name = "CH_NAME", length = 32)
	public String getChName() {
		return this.chName;
	}

	public void setChName(String chName) {
		this.chName = chName;
	}

	@Column(name = "EN_NAME", length = 32)
	public String getEnName() {
		return this.enName;
	}

	public void setEnName(String enName) {
		this.enName = enName;
	}

	@Column(name = "GENDER_TYPE", length = 1)
	public String getGenderType() {
		return this.genderType;
	}

	public void setGenderType(String genderType) {
		this.genderType = genderType;
	}

	@Column(name = "AGE")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "JOB_TITLE", length = 200)
	public String getJobTitle() {
		return this.jobTitle;
	}

	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}

	@Column(name = "ANNUAL_SALARY", precision = 20, scale = 5)
	public BigDecimal getAnnualSalary() {
		return this.annualSalary;
	}

	public void setAnnualSalary(BigDecimal annualSalary) {
		this.annualSalary = annualSalary;
	}

	@Column(name = "YEARS_OF_WORK")
	public Integer getYearsOfWork() {
		return this.yearsOfWork;
	}

	public void setYearsOfWork(Integer yearsOfWork) {
		this.yearsOfWork = yearsOfWork;
	}

	@Column(name = "COMP_TEL", length = 20)
	public String getCompTel() {
		return this.compTel;
	}

	public void setCompTel(String compTel) {
		this.compTel = compTel;
	}

	@Column(name = "COMP_ADDR", length = 40)
	public String getCompAddr() {
		return this.compAddr;
	}

	public void setCompAddr(String compAddr) {
		this.compAddr = compAddr;
	}

	@Column(name = "CURR_ADDR", length = 40)
	public String getCurrAddr() {
		return this.currAddr;
	}

	public void setCurrAddr(String currAddr) {
		this.currAddr = currAddr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BIRTHDAY", length = 10)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "ID_TYPE", length = 32)
	public String getIdType() {
		return this.idType;
	}

	public void setIdType(String idType) {
		this.idType = idType;
	}

	@Column(name = "ID_NO", length = 32)
	public String getIdNo() {
		return this.idNo;
	}

	public void setIdNo(String idNo) {
		this.idNo = idNo;
	}

	@Column(name = "TEL", length = 20)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "FIXED_TEL", length = 20)
	public String getFixedTel() {
		return this.fixedTel;
	}

	public void setFixedTel(String fixedTel) {
		this.fixedTel = fixedTel;
	}

	@Column(name = "EMAIL", length = 200)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "RELATIONSHIP", length = 100)
	public String getRelationship() {
		return this.relationship;
	}

	public void setRelationship(String relationship) {
		this.relationship = relationship;
	}

	@Column(name = "ZIP", length = 20)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "WORKPLACE", length = 100)
	public String getWorkplace() {
		return this.workplace;
	}

	public void setWorkplace(String workplace) {
		this.workplace = workplace;
	}

	@Column(name = "CREATOR", length = 40)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contacts")
	@JSONField(serialize = false)
	public Set<LoanorderAndContacts> getLoanorderAndContactses() {
		return this.loanorderAndContactses;
	}

	public void setLoanorderAndContactses(
			Set<LoanorderAndContacts> loanorderAndContactses) {
		this.loanorderAndContactses = loanorderAndContactses;
	}

	public Integer getCompProvince() {
		return compProvince;
	}

	public void setCompProvince(Integer compProvince) {
		this.compProvince = compProvince;
	}

	public Integer getCompCity() {
		return compCity;
	}

	public void setCompCity(Integer compCity) {
		this.compCity = compCity;
	}

	public String getCompAddrDetails() {
		return compAddrDetails;
	}

	public void setCompAddrDetails(String compAddrDetails) {
		this.compAddrDetails = compAddrDetails;
	}

	public Integer getFamilyProvince() {
		return familyProvince;
	}

	public void setFamilyProvince(Integer familyProvince) {
		this.familyProvince = familyProvince;
	}

	public Integer getFamilyCity() {
		return familyCity;
	}

	public void setFamilyCity(Integer familyCity) {
		this.familyCity = familyCity;
	}

	public String getFamilyAddrDetails() {
		return familyAddrDetails;
	}

	public void setFamilyAddrDetails(String familyAddrDetails) {
		this.familyAddrDetails = familyAddrDetails;
	}

	public Integer getCompArea() {
		return compArea;
	}

	public void setCompArea(Integer compArea) {
		this.compArea = compArea;
	}

	public Integer getFamilyArea() {
		return familyArea;
	}

	public void setFamilyArea(Integer familyArea) {
		this.familyArea = familyArea;
	}

}
