package com.qqms.model;

// Generated 015-6-17 10:6:05 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * LoanorderAndAccountinfo generated by hbmjava
 */
@Entity
@Table(name = "t_bp_loanorder_and_accountinfo")
public class LoanorderAndAccountinfo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String id;
	private AccountInfo accountInfo;
	private LoanOrder loanOrder;

	public LoanorderAndAccountinfo() {
	}

	public LoanorderAndAccountinfo(String id) {
		this.id = id;
	}

	public LoanorderAndAccountinfo(String id, AccountInfo accountInfo,
			LoanOrder loanOrder) {
		this.id = id;
		this.accountInfo = accountInfo;
		this.loanOrder = loanOrder;
	}

	@Id
	@GenericGenerator(name = "systemUUID", strategy = "uuid")
	@GeneratedValue(generator = "systemUUID")
	@Column(name = "ID", insertable = true, updatable = true, nullable = false, length = 40, unique = true)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCOUNT_ID")
	public AccountInfo getAccountInfo() {
		return this.accountInfo;
	}

	public void setAccountInfo(AccountInfo accountInfo) {
		this.accountInfo = accountInfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOAN_ORDER_ID")
	public LoanOrder getLoanOrder() {
		return this.loanOrder;
	}

	public void setLoanOrder(LoanOrder loanOrder) {
		this.loanOrder = loanOrder;
	}

}
