package com.qqms.model;

// Generated 2015-6-16 10:13:19 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * LoanorderAndContacts generated by hbm2java
 */
@Entity
@Table(name = "t_bp_loanorder_and_contacts")
public class LoanorderAndContacts implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String id;
	private Contacts contacts;
	private LoanOrder loanOrder;

	public LoanorderAndContacts() {
	}

	public LoanorderAndContacts(String id) {
		this.id = id;
	}

	public LoanorderAndContacts(String id, Contacts contacts,
			LoanOrder loanOrder) {
		this.id = id;
		this.contacts = contacts;
		this.loanOrder = loanOrder;
	}

	@Id
	@GenericGenerator(name = "systemUUID", strategy = "uuid")
	@GeneratedValue(generator = "systemUUID")
	@Column(name = "ID", insertable = true, updatable = true, nullable = false, length = 40, unique = true)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CONTACT_ID")
	public Contacts getContacts() {
		return this.contacts;
	}

	public void setContacts(Contacts contacts) {
		this.contacts = contacts;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOAN_ORDER_ID")
	public LoanOrder getLoanOrder() {
		return this.loanOrder;
	}

	public void setLoanOrder(LoanOrder loanOrder) {
		this.loanOrder = loanOrder;
	}

}
