package com.qqms.model;

// Generated 2015-6-24 10:29:40 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

import com.alibaba.fastjson.annotation.JSONField;

/**
 * LoanOrder generated by hbm2java
 */
@Entity
@Table(name = "t_bp_loan_order")
public class LoanOrder implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String loanOrderId;
	private Loaner loaner;
	private OrderStatus orderStatus;
	private String orderDesc;
	private String subjectType;
	private String loanType;
	private BigDecimal loanAmount;
	private BigDecimal loanMin;
	private Integer loanPeriod;
	private String repayMethod;
	private String purpose;
	private String creator;
	private String salesman;	
	private Date createDate;
	private Date finishDate;
	private Date applyDate;
	private String name;
	private String genderType;
	private String idNo;
	private Integer age;
	private String hukouAddr;
	private String curAddr;
	private String mobileTel;
	private String fixedTel;
	private String marriageType;
	private String hasChild;
	private String email;
	private String qqNo;
	private BigDecimal annualSalary;
	private String incomeSrc;
	private String mortgageStatus;
	private BigDecimal houseInstallPay;
	private BigDecimal rent;
	private String processStatus;
	private Set<LoanOrderHis> loanOrderHises = new HashSet<LoanOrderHis>(0);
	private Set<CreditAuditReport> creditAuditReports = new HashSet<CreditAuditReport>(
			0);
	private Set<LoanorderAndCompany> loanorderAndCompanies = new HashSet<LoanorderAndCompany>(
			0);
	private Set<LoanorderAndContacts> loanorderAndContactses = new HashSet<LoanorderAndContacts>(
			0);
	private Set<LoanorderAndAccountinfo> loanorderAndAccountinfos = new HashSet<LoanorderAndAccountinfo>(
			0);
	private Set<AuditInfoRecord> auditInfoRecords = new HashSet<AuditInfoRecord>(
			0);

	public LoanOrder() {
	}

	public LoanOrder(String loanOrderId) {
		this.loanOrderId = loanOrderId;
	}

	public LoanOrder(String loanOrderId, Loaner loaner,
			OrderStatus orderStatus, String orderDesc, String subjectType,
			String loanType, BigDecimal loanAmount, BigDecimal loanMin,
			Integer loanPeriod, String repayMethod, String purpose,
			String creator, Date createDate, Date finishDate,
			Date applyDate, String name, String genderType, String idNo,
			Integer age, String hukouAddr, String curAddr, String mobileTel,
			String fixedTel, String marriageType, String hasChild,
			String email, String qqNo, BigDecimal annualSalary,
			String incomeSrc, String mortgageStatus,
			BigDecimal houseInstallPay, BigDecimal rent, String processStatus,String salesman,
			Set<LoanOrderHis> loanOrderHises,
			Set<CreditAuditReport> creditAuditReports,
			Set<LoanorderAndCompany> loanorderAndCompanies,
			Set<LoanorderAndContacts> loanorderAndContactses,
			Set<LoanorderAndAccountinfo> loanorderAndAccountinfos,
			Set<AuditInfoRecord> auditInfoRecords) {
		this.loanOrderId = loanOrderId;
		this.loaner = loaner;
		this.orderStatus = orderStatus;
		this.orderDesc = orderDesc;
		this.subjectType = subjectType;
		this.loanType = loanType;
		this.loanAmount = loanAmount;
		this.loanMin = loanMin;
		this.loanPeriod = loanPeriod;
		this.repayMethod = repayMethod;
		this.purpose = purpose;
		this.creator = creator;
		this.createDate = createDate;
		this.finishDate = finishDate;
		this.applyDate = applyDate;
		this.name = name;
		this.genderType = genderType;
		this.idNo = idNo;
		this.age = age;
		this.hukouAddr = hukouAddr;
		this.curAddr = curAddr;
		this.mobileTel = mobileTel;
		this.fixedTel = fixedTel;
		this.marriageType = marriageType;
		this.hasChild = hasChild;
		this.email = email;
		this.qqNo = qqNo;
		this.annualSalary = annualSalary;
		this.incomeSrc = incomeSrc;
		this.mortgageStatus = mortgageStatus;
		this.houseInstallPay = houseInstallPay;
		this.rent = rent;
		this.salesman = salesman;
		this.processStatus = processStatus;
		this.loanOrderHises = loanOrderHises;
		this.creditAuditReports = creditAuditReports;
		this.loanorderAndCompanies = loanorderAndCompanies;
		this.loanorderAndContactses = loanorderAndContactses;
		this.loanorderAndAccountinfos = loanorderAndAccountinfos;
		this.auditInfoRecords = auditInfoRecords;
	}

	@Id
	@GenericGenerator(name = "systemUUID", strategy = "uuid")
	@GeneratedValue(generator = "systemUUID")
	@Column(name = "LOAN_ORDER_ID", insertable = true, updatable = true, nullable = false, length = 40, unique = true)
	public String getLoanOrderId() {
		return this.loanOrderId;
	}

	public void setLoanOrderId(String loanOrderId) {
		this.loanOrderId = loanOrderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOANER_ID")
	public Loaner getLoaner() {
		return this.loaner;
	}

	public void setLoaner(Loaner loaner) {
		this.loaner = loaner;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATUS_ID")
	public OrderStatus getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(OrderStatus orderStatus) {
		this.orderStatus = orderStatus;
	}

	@Column(name = "ORDER_DESC", length = 300)
	public String getOrderDesc() {
		return this.orderDesc;
	}

	public void setOrderDesc(String orderDesc) {
		this.orderDesc = orderDesc;
	}

	@Column(name = "SUBJECT_TYPE", length = 1)
	public String getSubjectType() {
		return this.subjectType;
	}

	public void setSubjectType(String subjectType) {
		this.subjectType = subjectType;
	}

	@Column(name = "LOAN_TYPE", length = 10)
	public String getLoanType() {
		return this.loanType;
	}

	public void setLoanType(String loanType) {
		this.loanType = loanType;
	}

	@Column(name = "LOAN_AMOUNT", precision = 20, scale = 5)
	public BigDecimal getLoanAmount() {
		return this.loanAmount;
	}

	public void setLoanAmount(BigDecimal loanAmount) {
		this.loanAmount = loanAmount;
	}

	@Column(name = "LOAN_MIN", precision = 20, scale = 5)
	public BigDecimal getLoanMin() {
		return this.loanMin;
	}

	public void setLoanMin(BigDecimal loanMin) {
		this.loanMin = loanMin;
	}

	@Column(name = "LOAN_PERIOD")
	public Integer getLoanPeriod() {
		return this.loanPeriod;
	}

	public void setLoanPeriod(Integer loanPeriod) {
		this.loanPeriod = loanPeriod;
	}

	@Column(name = "REPAY_METHOD", length = 1)
	public String getRepayMethod() {
		return this.repayMethod;
	}

	public void setRepayMethod(String repayMethod) {
		this.repayMethod = repayMethod;
	}

	@Column(name = "PURPOSE", length = 100)
	public String getPurpose() {
		return this.purpose;
	}

	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}

	@Column(name = "CREATOR", length = 100)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FINISH_DATE", length = 19)
	public Date getFinishDate() {
		return this.finishDate;
	}

	public void setFinishDate(Date finishDate) {
		this.finishDate = finishDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "APPLY_DATE", length = 10)
	public Date getApplyDate() {
		return this.applyDate;
	}

	public void setApplyDate(Date applyDate) {
		this.applyDate = applyDate;
	}

	@Column(name = "NAME", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "GENDER_TYPE", length = 1)
	public String getGenderType() {
		return this.genderType;
	}

	public void setGenderType(String genderType) {
		this.genderType = genderType;
	}

	@Column(name = "ID_NO", length = 32)
	public String getIdNo() {
		return this.idNo;
	}

	public void setIdNo(String idNo) {
		this.idNo = idNo;
	}

	@Column(name = "AGE")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "HUKOU_ADDR", length = 40)
	public String getHukouAddr() {
		return hukouAddr;
	}
	
	public void setHukouAddr(String hukouAddr) {
		this.hukouAddr = hukouAddr;
	}
	

	@Column(name = "CUR_ADDR", length = 40)
	public String getCurAddr() {
		return this.curAddr;
	}


	public void setCurAddr(String curAddr) {
		this.curAddr = curAddr;
	}

	@Column(name = "MOBILE_TEL", length = 20)
	public String getMobileTel() {
		return this.mobileTel;
	}

	public void setMobileTel(String mobileTel) {
		this.mobileTel = mobileTel;
	}

	@Column(name = "FIXED_TEL", length = 20)
	public String getFixedTel() {
		return this.fixedTel;
	}

	public void setFixedTel(String fixedTel) {
		this.fixedTel = fixedTel;
	}

	@Column(name = "MARRIAGE_TYPE", length = 1)
	public String getMarriageType() {
		return this.marriageType;
	}

	public void setMarriageType(String marriageType) {
		this.marriageType = marriageType;
	}

	@Column(name = "HAS_CHILD", length = 1)
	public String getHasChild() {
		return this.hasChild;
	}

	public void setHasChild(String hasChild) {
		this.hasChild = hasChild;
	}

	@Column(name = "EMAIL", length = 300)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "QQ_NO", length = 30)
	public String getQqNo() {
		return this.qqNo;
	}

	public void setQqNo(String qqNo) {
		this.qqNo = qqNo;
	}

	@Column(name = "ANNUAL_SALARY", precision = 20, scale = 5)
	public BigDecimal getAnnualSalary() {
		return this.annualSalary;
	}

	public void setAnnualSalary(BigDecimal annualSalary) {
		this.annualSalary = annualSalary;
	}

	@Column(name = "INCOME_SRC", length = 200)
	public String getIncomeSrc() {
		return this.incomeSrc;
	}

	public void setIncomeSrc(String incomeSrc) {
		this.incomeSrc = incomeSrc;
	}

	@Column(name = "MORTGAGE_STATUS", length = 1)
	public String getMortgageStatus() {
		return this.mortgageStatus;
	}

	public void setMortgageStatus(String mortgageStatus) {
		this.mortgageStatus = mortgageStatus;
	}

	@Column(name = "HOUSE_INSTALL_PAY", precision = 20, scale = 5)
	public BigDecimal getHouseInstallPay() {
		return this.houseInstallPay;
	}

	public void setHouseInstallPay(BigDecimal houseInstallPay) {
		this.houseInstallPay = houseInstallPay;
	}

	@Column(name = "RENT", precision = 20, scale = 5)
	public BigDecimal getRent() {
		return this.rent;
	}

	public void setRent(BigDecimal rent) {
		this.rent = rent;
	}

	@Column(name = "PROCESS_STATUS", length = 10)
	public String getProcessStatus() {
		return this.processStatus;
	}

	public void setProcessStatus(String processStatus) {
		this.processStatus = processStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loanOrder")
	@JSONField(serialize = false)
	public Set<LoanOrderHis> getLoanOrderHises() {
		return this.loanOrderHises;
	}

	public void setLoanOrderHises(Set<LoanOrderHis> loanOrderHises) {
		this.loanOrderHises = loanOrderHises;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loanOrder")
	@JSONField(serialize = false)
	public Set<CreditAuditReport> getCreditAuditReports() {
		return this.creditAuditReports;
	}

	public void setCreditAuditReports(Set<CreditAuditReport> creditAuditReports) {
		this.creditAuditReports = creditAuditReports;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loanOrder")
	@JSONField(serialize = false)
	public Set<LoanorderAndCompany> getLoanorderAndCompanies() {
		return this.loanorderAndCompanies;
	}

	public void setLoanorderAndCompanies(
			Set<LoanorderAndCompany> loanorderAndCompanies) {
		this.loanorderAndCompanies = loanorderAndCompanies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loanOrder")
	@JSONField(serialize = false)
	public Set<LoanorderAndContacts> getLoanorderAndContactses() {
		return this.loanorderAndContactses;
	}

	public void setLoanorderAndContactses(
			Set<LoanorderAndContacts> loanorderAndContactses) {
		this.loanorderAndContactses = loanorderAndContactses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loanOrder")
	@JSONField(serialize = false)
	public Set<LoanorderAndAccountinfo> getLoanorderAndAccountinfos() {
		return this.loanorderAndAccountinfos;
	}

	public void setLoanorderAndAccountinfos(
			Set<LoanorderAndAccountinfo> loanorderAndAccountinfos) {
		this.loanorderAndAccountinfos = loanorderAndAccountinfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loanOrder")
	@JSONField(serialize = false)
	public Set<AuditInfoRecord> getAuditInfoRecords() {
		return this.auditInfoRecords;
	}

	public void setAuditInfoRecords(Set<AuditInfoRecord> auditInfoRecords) {
		this.auditInfoRecords = auditInfoRecords;
	}
	
	@Column(name = "salesman", length = 40)
	public String getSalesman() {
		return salesman;
	}

	public void setSalesman(String salesman) {
		this.salesman = salesman;
	}		

}
