package com.qqms.model;

// Generated 2015-6-16 14:42:49 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TSysParameter generated by hbm2java
 */
@Entity
@Table(name = "t_sys_parameter")
public class Parameter implements java.io.Serializable {

	private Integer pramId;
	private String parmCode;
	private String parmName;
	private String parmValue;
	private char status;
	private Date createDate;
	private Integer creator;
	private Date updateDate;
	private Integer updater;
	private String description;

	public Parameter() {
	}

	public Parameter(String parmCode, String parmName, String parmValue,
			char status) {
		this.parmCode = parmCode;
		this.parmName = parmName;
		this.parmValue = parmValue;
		this.status = status;
	}

	public Parameter(String parmCode, String parmName, String parmValue,
			char status, Date createDate, Integer creator, Date updateDate,
			Integer updater, String description) {
		this.parmCode = parmCode;
		this.parmName = parmName;
		this.parmValue = parmValue;
		this.status = status;
		this.createDate = createDate;
		this.creator = creator;
		this.updateDate = updateDate;
		this.updater = updater;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PRAM_ID", unique = true, nullable = false)
	public Integer getPramId() {
		return this.pramId;
	}

	public void setPramId(Integer pramId) {
		this.pramId = pramId;
	}

	@Column(name = "PARM_CODE", nullable = false, length = 50)
	public String getParmCode() {
		return this.parmCode;
	}

	public void setParmCode(String parmCode) {
		this.parmCode = parmCode;
	}

	@Column(name = "PARM_NAME", nullable = false, length = 100)
	public String getParmName() {
		return this.parmName;
	}

	public void setParmName(String parmName) {
		this.parmName = parmName;
	}

	@Column(name = "PARM_VALUE", nullable = false, length = 100)
	public String getParmValue() {
		return this.parmValue;
	}

	public void setParmValue(String parmValue) {
		this.parmValue = parmValue;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "CREATOR")
	public Integer getCreator() {
		return this.creator;
	}

	public void setCreator(Integer creator) {
		this.creator = creator;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATE", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "UPDATER")
	public Integer getUpdater() {
		return this.updater;
	}

	public void setUpdater(Integer updater) {
		this.updater = updater;
	}

	@Column(name = "DESCRIPTION", length = 512)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
