package com.oasys.model;

// Generated 2015-10-10 14:43:11 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TOaAttachment generated by hbm2java
 */
@Entity
@Table(name = "t_oa_attachment")
@SuppressWarnings("serial")
public class Attachment implements java.io.Serializable {

	private Integer attId;
	private String appRegNo;
	private Integer detailId;
	private String attName;
	private byte[] attData;
	private String fileType;
	private String attURL;
	private String attDesc;
	private String creator;
	private Date createDatetime;
	

	public Attachment() {
	}

	public Attachment(String appRegNo,Integer detailId, String attName, byte[] attData,String attURL,
			String fileType, String attDesc, String creator, Date createDatetime) {
		this.appRegNo = appRegNo;
		this.detailId=detailId;
		this.attName = attName;
		this.attData = attData;
		this.fileType = fileType;
		this.attURL=attURL;
		this.attDesc = attDesc;
		this.creator = creator;
		this.createDatetime = createDatetime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ATT_ID", unique = true, nullable = false)
	public Integer getAttId() {
		return this.attId;
	}

	public void setAttId(Integer attId) {
		this.attId = attId;
	}

	@Column(name = "APP_REG_NO", length = 25)
	public String getAppRegNo() {
		return this.appRegNo;
	}

	public void setAppRegNo(String appRegNo) {
		this.appRegNo = appRegNo;
	}

	@Column(name = "DETAIL_ID")
	public Integer getDetailId() {
		return detailId;
	}

	public void setDetailId(Integer detailId) {
		this.detailId = detailId;
	}

	@Column(name = "ATT_NAME", length = 50)
	public String getAttName() {
		return this.attName;
	}

	public void setAttName(String attName) {
		this.attName = attName;
	}

	@Column(name = "ATT_DATA")
	public byte[] getAttData() {
		return this.attData;
	}

	public void setAttData(byte[] attData) {
		this.attData = attData;
	}

	@Column(name = "FILE_TYPE", length = 10)
	public String getFileType() {
		return this.fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

	@Column(name = "ATT_URL", length = 255)
	public String getAttURL() {
		return attURL;
	}

	public void setAttURL(String attURL) {
		this.attURL = attURL;
	}
	
	@Column(name = "ATT_DESC", length = 200)
	public String getAttDesc() {
		return this.attDesc;
	}

	public void setAttDesc(String attDesc) {
		this.attDesc = attDesc;
	}

	@Column(name = "CREATOR", length = 40)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATETIME", length = 19)
	public Date getCreateDatetime() {
		return this.createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

}
