package com.oasys.model;

// Generated 2015-9-25 14:45:11 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Transient;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TOaAdBadgeAppAttach generated by hbm2java
 */
@Entity
@Table(name = "t_oa_ad_badge_app_attach", catalog = "oasys")
public class BadgeAppAttach implements java.io.Serializable ,Cloneable{

	private Integer pnrId;
	private String appNo;
	private Integer applicantNo;
	private String namePinyin;
	//职位编码
	private String position;
	private Integer deptNo;
	private String remark;

	//部门名称
	private String fullName;
	//申请人名字
	private String name;
	/*//角色id
	private Integer roleId;*/
	
	//职位名字
	private String positionName;
	
	
	public BadgeAppAttach() {
	}

	public BadgeAppAttach(String appNo, Integer applicantNo,
			String namePinyin, String position, Integer deptNo, String remark) {
		this.appNo = appNo;
		this.applicantNo = applicantNo;
		this.namePinyin = namePinyin;
		this.position = position;
		this.deptNo = deptNo;
		this.remark = remark;
	}

	
	@Transient
	public String getPositionName() {
		return positionName;
	}

	public void setPositionName(String positionName) {
		this.positionName = positionName;
	}

	@Transient
	public String getFullName() {
		return fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}
	@Transient
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	/*@Transient
	public Integer getRoleId() {
		return roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}*/

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PNR_ID", unique = true, nullable = false)
	public Integer getPnrId() {
		return this.pnrId;
	}

	public void setPnrId(Integer pnrId) {
		this.pnrId = pnrId;
	}

	@Column(name = "APP_NO", length = 25)
	public String getAppNo() {
		return this.appNo;
	}

	public void setAppNo(String appNo) {
		this.appNo = appNo;
	}

	@Column(name = "APPLICANT_NO")
	public Integer getApplicantNo() {
		return this.applicantNo;
	}

	public void setApplicantNo(Integer applicantNo) {
		this.applicantNo = applicantNo;
	}

	@Column(name = "NAME_PINYIN", length = 30)
	public String getNamePinyin() {
		return this.namePinyin;
	}

	public void setNamePinyin(String namePinyin) {
		this.namePinyin = namePinyin;
	}

	@Column(name = "POSITION", length = 50)
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	@Column(name = "DEPT_NO")
	public Integer getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(Integer deptNo) {
		this.deptNo = deptNo;
	}

	@Column(name = "REMARK", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Override
    public Object clone(){
    	try {
			return super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
    	return null;
    }
	
}
