package com.oasys.model;

// Generated 2015-9-25 14:45:11 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * TOaAdBadgeApp generated by hbm2java
 */
@Entity
@Table(name = "t_oa_ad_badge_app", catalog = "oasys")
public class BadgeApp implements java.io.Serializable {

	private Integer pnrId;
	private Integer registrantNo;
	private Date regDatetime;
	private String appNo;
	private Date appDate;
	private String appStatus;
	private String procStatus;
	private String remark;
	//登记人名字
	private String regName;
	
	//开始申请时间
	private String appDateS;
	//结束时间
	private String appDateE;
	//申请状态名称
	private String appStateName;
	
	
	public BadgeApp() {
	}

	public BadgeApp(Integer registrantNo, Date regDatetime, String appNo,
			Date appDate, String appStatus, String procStatus, String remark) {
		this.registrantNo = registrantNo;
		this.regDatetime = regDatetime;
		this.appNo = appNo;
		this.appDate = appDate;
		this.appStatus = appStatus;
		this.procStatus = procStatus;
		this.remark = remark;
	}
	

	@Transient
	public String getRegName() {
		return regName;
	}

	public void setRegName(String regName) {
		this.regName = regName;
	}

	@Transient
	public String getAppDateS() {
		return appDateS;
	}

	public void setAppDateS(String appDateS) {
		this.appDateS = appDateS;
	}
	@Transient
	public String getAppDateE() {
		return appDateE;
	}

	public void setAppDateE(String appDateE) {
		this.appDateE = appDateE;
	}
	@Transient
	public String getAppStateName() {
		return appStateName;
	}

	public void setAppStateName(String appStateName) {
		this.appStateName = appStateName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PNR_ID", unique = true, nullable = false)
	public Integer getPnrId() {
		return this.pnrId;
	}

	public void setPnrId(Integer pnrId) {
		this.pnrId = pnrId;
	}

	@Column(name = "REGISTRANT_NO")
	public Integer getRegistrantNo() {
		return this.registrantNo;
	}

	public void setRegistrantNo(Integer registrantNo) {
		this.registrantNo = registrantNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REG_DATETIME", length = 19)
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	public Date getRegDatetime() {
		return this.regDatetime;
	}

	public void setRegDatetime(Date regDatetime) {
		this.regDatetime = regDatetime;
	}

	@Column(name = "APP_NO", length = 25)
	public String getAppNo() {
		return this.appNo;
	}

	public void setAppNo(String appNo) {
		this.appNo = appNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "APP_DATE", length = 10)
	@DateTimeFormat(pattern="yyyy-MM-dd")
	public Date getAppDate() {
		return this.appDate;
	}

	public void setAppDate(Date appDate) {
		this.appDate = appDate;
	}

	@Column(name = "APP_STATUS", length = 100)
	public String getAppStatus() {
		return this.appStatus;
	}

	public void setAppStatus(String appStatus) {
		this.appStatus = appStatus;
	}

	@Column(name = "PROC_STATUS", length = 1)
	public String getProcStatus() {
		return this.procStatus;
	}

	public void setProcStatus(String procStatus) {
		this.procStatus = procStatus;
	}

	@Column(name = "REMARK", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
