package com.oasys.model;

// Generated 2015-9-23 15:26:54 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import com.oasys.viewModel.WorkFlowTasksModel;

/**
 * TOaAdConsumablesApp generated by hbm2java
 */
@Entity
@Table(name = "t_oa_ad_consumables_app", uniqueConstraints = @UniqueConstraint(columnNames = "APP_NO"))
public class ConsumablesApp implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer caId;
	private String appNo;
	private Integer applicantNo;
	private Integer appDept;
	private String appDate;
	private String appStatus;
	private String procStatus;
	private String remark;
	private String account;
	private String appDeptName;
	private String appDateBefore;//查询申请时间开始绑定字段
	private String appDateAfter;//查询申请时间结束绑定字段
	/** WorkFlow propertites */
	private WorkFlowTasksModel taskModel;//task对象
	private String result;//审批通过或驳回标识
	private String taskID;//任务taskID
	private String formKey;//跳转对应的受理页面JSP配置(在流程图的formKey中设置)
	private String assistant;//指定的候选人
	private String isSuccess;//是否通过标识
	private String resourcesName;//资源文件名称
	private BigDecimal allAmt;
	public ConsumablesApp() {
	}
	
	public ConsumablesApp(Integer caId, String appNo, Integer applicantNo,
			Integer appDept, String appDate, String appStatus,
			String procStatus, String remark, String account,
			String appDeptName, WorkFlowTasksModel taskModel, String result,
			String taskID, String formKey, String assistant, String isSuccess,
			String resourcesName,BigDecimal allAmt) {
		super();
		this.caId = caId;
		this.appNo = appNo;
		this.applicantNo = applicantNo;
		this.appDept = appDept;
		this.appDate = appDate;
		this.appStatus = appStatus;
		this.procStatus = procStatus;
		this.remark = remark;
		this.account = account;
		this.appDeptName = appDeptName;
		this.taskModel = taskModel;
		this.result = result;
		this.taskID = taskID;
		this.formKey = formKey;
		this.assistant = assistant;
		this.isSuccess = isSuccess;
		this.resourcesName = resourcesName;
		this.allAmt=allAmt;
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CA_ID", unique = true, nullable = false)
	public Integer getCaId() {
		return this.caId;
	}

	public void setCaId(Integer caId) {
		this.caId = caId;
	}

	@Column(name = "APP_NO", unique = true, length = 25)
	public String getAppNo() {
		return this.appNo;
	}

	public void setAppNo(String appNo) {
		this.appNo = appNo;
	}

	@Column(name = "APPLICANT_NO")
	public Integer getApplicantNo() {
		return this.applicantNo;
	}

	public void setApplicantNo(Integer applicantNo) {
		this.applicantNo = applicantNo;
	}

	@Column(name = "APP_DEPT")
	public Integer getAppDept() {
		return this.appDept;
	}

	public void setAppDept(Integer appDept) {
		this.appDept = appDept;
	}

	
	@Column(name = "APP_DATE", length = 10)
	public String getAppDate() {
		return this.appDate;
	}

	public void setAppDate(String appDate) {
		this.appDate = appDate;
	}

	@Column(name = "APP_STATUS", length = 100)
	public String getAppStatus() {
		return this.appStatus;
	}

	public void setAppStatus(String appStatus) {
		this.appStatus = appStatus;
	}

	@Column(name = "PROC_STATUS", length = 1)
	public String getProcStatus() {
		return this.procStatus;
	}

	public void setProcStatus(String procStatus) {
		this.procStatus = procStatus;
	}

	@Column(name = "REMARK", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
	@Transient
	public String getAccount() {
		return account;
	}

	public void setAccount(String account) {
		this.account = account;
	}
	@Transient
	public String getAppDeptName() {
		return appDeptName;
	}

	public void setAppDeptName(String appDeptName) {
		this.appDeptName = appDeptName;
	}
	@Transient
	public WorkFlowTasksModel getTaskModel() {
		return taskModel;
	}

	public void setTaskModel(WorkFlowTasksModel taskModel) {
		this.taskModel = taskModel;
	}
	@Transient
	public String getResult() {
		return result;
	}

	public void setResult(String result) {
		this.result = result;
	}
	@Transient
	public String getTaskID() {
		return taskID;
	}

	public void setTaskID(String taskID) {
		this.taskID = taskID;
	}
	@Transient
	public String getFormKey() {
		return formKey;
	}

	public void setFormKey(String formKey) {
		this.formKey = formKey;
	}
	@Transient
	public String getAssistant() {
		return assistant;
	}

	public void setAssistant(String assistant) {
		this.assistant = assistant;
	}
	@Transient
	public String getIsSuccess() {
		return isSuccess;
	}

	public void setIsSuccess(String isSuccess) {
		this.isSuccess = isSuccess;
	}
	@Transient
	public String getResourcesName() {
		return resourcesName;
	}

	public void setResourcesName(String resourcesName) {
		this.resourcesName = resourcesName;
	}
	@Transient
	public String getAppDateBefore() {
		return appDateBefore;
	}

	public void setAppDateBefore(String appDateBefore) {
		this.appDateBefore = appDateBefore;
	}
	@Transient
	public String getAppDateAfter() {
		return appDateAfter;
	}

	public void setAppDateAfter(String appDateAfter) {
		this.appDateAfter = appDateAfter;
	}
	@Column(name = "ALL_AMT", precision = 10)
	public BigDecimal getAllAmt() {
		return allAmt;
	}

	public void setAllAmt(BigDecimal allAmt) {
		this.allAmt = allAmt;
	}
	
}
