package com.oasys.model;

// Generated 2015-9-23 15:26:54 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Transient;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TOaAdConsumablesAppAttach generated by hbm2java
 */
@Entity
@Table(name = "t_oa_ad_consumables_app_attach", uniqueConstraints = @UniqueConstraint(columnNames = "APP_NO"))
public class ConsumablesAppAttach implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer caaId;
	private String appNo;
	private String goodsName;
	private String model;
	private String unit;
	private Integer stock;
	private BigDecimal price;
	private Integer qty;
	private BigDecimal totalAmt;
	private ConsumablesApp consumablesApp;
	public ConsumablesAppAttach() {
	}

	public ConsumablesAppAttach(String appNo, String goodsName,
			String model, String unit, Integer stock, BigDecimal price,
			Integer qty, BigDecimal totalAmt,ConsumablesApp consumablesApp) {
		this.appNo = appNo;
		this.goodsName = goodsName;
		this.model = model;
		this.unit = unit;
		this.stock = stock;
		this.price = price;
		this.qty = qty;
		this.totalAmt = totalAmt;
		this.consumablesApp=consumablesApp;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CAA_ID", unique = true, nullable = false)
	public Integer getCaaId() {
		return this.caaId;
	}

	public void setCaaId(Integer caaId) {
		this.caaId = caaId;
	}

	@Column(name = "APP_NO", unique = true, length = 25)
	public String getAppNo() {
		return this.appNo;
	}

	public void setAppNo(String appNo) {
		this.appNo = appNo;
	}

	@Column(name = "GOODS_NAME", length = 30)
	public String getGoodsName() {
		return this.goodsName;
	}

	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName;
	}

	@Column(name = "MODEL", length = 50)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Column(name = "UNIT", length = 10)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Column(name = "STOCK")
	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	@Column(name = "PRICE", precision = 8)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "QTY")
	public Integer getQty() {
		return this.qty;
	}

	public void setQty(Integer qty) {
		this.qty = qty;
	}

	@Column(name = "TOTAL_AMT", precision = 10)
	public BigDecimal getTotalAmt() {
		return this.totalAmt;
	}

	public void setTotalAmt(BigDecimal totalAmt) {
		this.totalAmt = totalAmt;
	}
	@Transient
	public ConsumablesApp getConsumablesApp() {
		return consumablesApp;
	}

	public void setConsumablesApp(ConsumablesApp consumablesApp) {
		this.consumablesApp = consumablesApp;
	}
	
}
