package com.oasys.model;

// Generated 2015-10-14 10:29:36 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TOaAdGoodsTackoverStacfg generated by hbm2java
 */
@Entity
@Table(name = "t_oa_ad_goods_tackover_stacfg")
@SuppressWarnings("serial")
public class GoodsTackoverStacfg implements java.io.Serializable {

	private Integer gtsId;
	private String goodsName;
	private String goodsType;
	private String brandModel;
	private String unit;
	private Integer qty;
	private List<GoodsTackoverReg> goodsTackoveRegList = new ArrayList<GoodsTackoverReg>();
	public GoodsTackoverStacfg() {
	}

	public GoodsTackoverStacfg(String goodsName, String goodsType,
			String brandModel, String unit, Integer qty,
			List<GoodsTackoverReg> goodsTackoveRegList) {
		this.goodsName = goodsName;
		this.brandModel = brandModel;
		this.unit = unit;
		this.qty = qty;
		this.goodsType = goodsType;
		this.goodsTackoveRegList = goodsTackoveRegList;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "GTS_ID", unique = true, nullable = false)
	public Integer getGtsId() {
		return this.gtsId;
	}

	public void setGtsId(Integer gtsId) {
		this.gtsId = gtsId;
	}

	@Column(name = "GOODS_NAME", length = 50)
	public String getGoodsName() {
		return this.goodsName;
	}

	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName;
	}

	@Column(name = "GOODS_TYPE")
	public String getGoodsType() {
		return goodsType;
	}

	public void setGoodsType(String goodsType) {
		this.goodsType = goodsType;
	}

	@Column(name = "BRAND_MODEL", length = 50)
	public String getBrandModel() {
		return this.brandModel;
	}

	public void setBrandModel(String brandModel) {
		this.brandModel = brandModel;
	}

	@Column(name = "UNIT", length = 10)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Column(name = "QTY")
	public Integer getQty() {
		return this.qty;
	}

	public void setQty(Integer qty) {
		this.qty = qty;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "t_oa_ad_goodstackover_and_stacfg", joinColumns = { @JoinColumn(name = "GTS_ID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "GTR_ID", nullable = false, updatable = false) })
	public List<GoodsTackoverReg> getGoodsTackoveRegList() {
		return goodsTackoveRegList;
	}

	public void setGoodsTackoveRegList(List<GoodsTackoverReg> goodsTackoveRegList) {
		this.goodsTackoveRegList = goodsTackoveRegList;
	}

	
}
