package com.oasys.model;

// Generated 2015-10-14 10:29:36 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * TOaAdPpeBorrowReg generated by hbm2java
 * 固定资产借用登记
 */
@Entity
@Table(name = "t_oa_ad_ppe_borrow_reg")
public class PpeBorrowReg implements java.io.Serializable,Cloneable {

	private Integer pbrId;
	private Integer registrantNo;
	private Date regDatetime;
	private Integer borrower;
	private Integer deptNo;
	private Integer reverter;
	private Date revDatetime;
	private String ppeNo;
	private String ppeName;
	private String model;
	private String borReson;
	private String remark;
	
	/**
	 * 登记人姓名
	 */
	private String registrantName;
	/**
	 * 借用人姓名
	 */
	private String borrowerName;
	/**
	 * 借用部门
	 */
	private String fullName;
	/**
	 * 归还人部门id
	 */
	private Integer reverterDeptNo;
	/**
	 * 归还人姓名
	 */
	private String reverterName;
	/**
	 * 条件归还日期开始
	 */
	private String AppDateS;
	/**
	 * 条件归还日期结束
	 */
	private String AppDateE;
	

	public PpeBorrowReg() {
	}

	
	


	
	public PpeBorrowReg(Integer pbrId, Integer registrantNo, Date regDatetime,
			Integer borrower, Integer deptNo, Integer reverter,
			Date revDatetime, String ppeNo, String ppeName, String model,
			String borReson, String remark, String registrantName,
			String borrowerName, String fullName, Integer reverterDeptNo,String reverterName,
			String ifRevDatetime) {
		super();
		this.pbrId = pbrId;
		this.registrantNo = registrantNo;
		this.regDatetime = regDatetime;
		this.borrower = borrower;
		this.deptNo = deptNo;
		this.reverter = reverter;
		this.revDatetime = revDatetime;
		this.ppeNo = ppeNo;
		this.ppeName = ppeName;
		this.model = model;
		this.borReson = borReson;
		this.remark = remark;
		this.reverterDeptNo=reverterDeptNo;
		this.registrantName = registrantName;
		this.borrowerName = borrowerName;
		this.fullName = fullName;
		this.reverterName = reverterName;
	}


	
	@Transient
	public Integer getReverterDeptNo() {
		return reverterDeptNo;
	}

	public void setReverterDeptNo(Integer reverterDeptNo) {
		this.reverterDeptNo = reverterDeptNo;
	}

	@Transient
	public String getAppDateS() {
		return AppDateS;
	}

	public void setAppDateS(String appDateS) {
		AppDateS = appDateS;
	}

	@Transient
	public String getAppDateE() {
		return AppDateE;
	}


	public void setAppDateE(String appDateE) {
		AppDateE = appDateE;
	}


	@Transient
	public String getFullName() {
		return fullName;
	}



	public void setFullName(String fullName) {
		this.fullName = fullName;
	}



	@Transient
	public String getRegistrantName() {
		return registrantName;
	}

	public void setRegistrantName(String registrantName) {
		this.registrantName = registrantName;
	}
	@Transient
	public String getBorrowerName() {
		return borrowerName;
	}

	public void setBorrowerName(String borrowerName) {
		this.borrowerName = borrowerName;
	}
	@Transient
	public String getReverterName() {
		return reverterName;
	}

	public void setReverterName(String reverterName) {
		this.reverterName = reverterName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PBR_ID", unique = true, nullable = false)
	public Integer getPbrId() {
		return this.pbrId;
	}

	public void setPbrId(Integer pbrId) {
		this.pbrId = pbrId;
	}

	@Column(name = "REGISTRANT_NO")
	public Integer getRegistrantNo() {
		return this.registrantNo;
	}

	public void setRegistrantNo(Integer registrantNo) {
		this.registrantNo = registrantNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REG_DATETIME", length = 19)
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	public Date getRegDatetime() {
		return this.regDatetime;
	}

	public void setRegDatetime(Date regDatetime) {
		this.regDatetime = regDatetime;
	}

	@Column(name = "BORROWER")
	public Integer getBorrower() {
		return this.borrower;
	}

	public void setBorrower(Integer borrower) {
		this.borrower = borrower;
	}

	@Column(name = "DEPT_NO")
	public Integer getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(Integer deptNo) {
		this.deptNo = deptNo;
	}

	@Column(name = "REVERTER")
	public Integer getReverter() {
		return this.reverter;
	}

	public void setReverter(Integer reverter) {
		this.reverter = reverter;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REV_DATETIME", length = 19)
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	public Date getRevDatetime() {
		return this.revDatetime;
	}

	public void setRevDatetime(Date revDatetime) {
		this.revDatetime = revDatetime;
	}

	@Column(name = "PPE_NO", length = 20)
	public String getPpeNo() {
		return this.ppeNo;
	}

	public void setPpeNo(String ppeNo) {
		this.ppeNo = ppeNo;
	}

	@Column(name = "PPE_NAME", length = 50)
	public String getPpeName() {
		return this.ppeName;
	}

	public void setPpeName(String ppeName) {
		this.ppeName = ppeName;
	}

	@Column(name = "MODEL", length = 50)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Column(name = "BOR_RESON", length = 200)
	public String getBorReson() {
		return this.borReson;
	}

	public void setBorReson(String borReson) {
		this.borReson = borReson;
	}

	@Column(name = "REMARK", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
	
	@Override
    public Object clone(){
    	try {
			return super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
    	return null;
    }

}
