package com.oasys.model;

// Generated 2015-10-10 14:43:11 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * TOaAdPpeReg generated by hbm2java
 */
@Entity
@Table(name = "t_oa_ad_ppe_reg")
public class PpeReg implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = -607094681227927278L;
	
	
	private Integer prId;
	private Integer registrantNo;//登记人
	private String regDatetime;//登记日期
	private String ppeNo;//资产编号
	private String ppeName;//资产名称
	private String ppeModel;//资产规格
	private Integer qty;//数量
	private BigDecimal price;//购买价格
	private Integer useDept;//使用部门
	private Integer user;//使用人
	private String remark;//备注
	
	private String orgName;//部门名称
	private String userName;//用户名称
	private String ppeUserName;//使用部门
	private String ppeOrgName;//使用名称
	private String regDatetimeBegin;
	private String regDatetimeEnd;
	
	

	public PpeReg() {
	}

	public PpeReg(Integer registrantNo, String regDatetime, String ppeNo,
			String ppeName, String ppeModel, Integer qty, BigDecimal price,
			Integer useDept, Integer user, String remark) {
		this.registrantNo = registrantNo;
		this.regDatetime = regDatetime;
		this.ppeNo = ppeNo;
		this.ppeName = ppeName;
		this.ppeModel = ppeModel;
		this.qty = qty;
		this.price = price;
		this.useDept = useDept;
		this.user = user;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PR_ID", unique = true, nullable = false)
	public Integer getPrId() {
		return this.prId;
	}

	public void setPrId(Integer prId) {
		this.prId = prId;
	}

	@Column(name = "REGISTRANT_NO")
	public Integer getRegistrantNo() {
		return this.registrantNo;
	}

	public void setRegistrantNo(Integer registrantNo) {
		this.registrantNo = registrantNo;
	}

	@Column(name = "REG_DATETIME", length = 19)
	public String getRegDatetime() {
		return this.regDatetime;
	}

	public void setRegDatetime(String regDatetime) {
		this.regDatetime = regDatetime;
	}

	@Column(name = "PPE_NO", length = 20)
	public String getPpeNo() {
		return this.ppeNo;
	}

	public void setPpeNo(String ppeNo) {
		this.ppeNo = ppeNo;
	}

	@Column(name = "PPE_NAME", length = 50)
	public String getPpeName() {
		return this.ppeName;
	}

	public void setPpeName(String ppeName) {
		this.ppeName = ppeName;
	}

	@Column(name = "PPE_MODEL", length = 50)
	public String getPpeModel() {
		return this.ppeModel;
	}

	public void setPpeModel(String ppeModel) {
		this.ppeModel = ppeModel;
	}

	@Column(name = "QTY")
	public Integer getQty() {
		return this.qty;
	}

	public void setQty(Integer qty) {
		this.qty = qty;
	}

	@Column(name = "PRICE", precision = 10)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "USE_DEPT")
	public Integer getUseDept() {
		return this.useDept;
	}

	public void setUseDept(Integer useDept) {
		this.useDept = useDept;
	}

	@Column(name = "USER")
	public Integer getUser() {
		return this.user;
	}

	public void setUser(Integer user) {
		this.user = user;
	}

	@Column(name = "REMARK", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Transient
	public String getOrgName() {
		return orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}
	
	@Transient
	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}
	
	@Transient
	public String getRegDatetimeBegin() {
		return regDatetimeBegin;
	}

	public void setRegDatetimeBegin(String regDatetimeBegin) {
		this.regDatetimeBegin = regDatetimeBegin;
	}
	@Transient
	public String getRegDatetimeEnd() {
		return regDatetimeEnd;
	}

	public void setRegDatetimeEnd(String regDatetimeEnd) {
		this.regDatetimeEnd = regDatetimeEnd;
	}
	
	@Transient
	public String getPpeUserName() {
		return ppeUserName;
	}

	public void setPpeUserName(String ppeUserName) {
		this.ppeUserName = ppeUserName;
	}

	@Transient
	public String getPpeOrgName() {
		return ppeOrgName;
	}

	public void setPpeOrgName(String ppeOrgName) {
		this.ppeOrgName = ppeOrgName;
	}

	
}
