package com.oasys.model;

// Generated 2015-9-24 9:33:54 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Transient;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TOaAdPpeTurnoverAttach generated by hbm2java
 */
@Entity
@Table(name = "t_oa_ad_ppe_turnover_attach")
public class PpeTurnoverAttach implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer ptaId;
	private String appNo;
	private String ppeNo;
	private String ppeName;
	private String model;
	private String unit;
	private Integer qty;
	private BigDecimal ppeAmt;
	private PpeTurnoverApp ppeTurnoverApp;
	@Transient
	public PpeTurnoverApp getPpeTurnoverApp() {
		return ppeTurnoverApp;
	}

	public void setPpeTurnoverApp(PpeTurnoverApp ppeTurnoverApp) {
		this.ppeTurnoverApp = ppeTurnoverApp;
	}

	public PpeTurnoverAttach() {
	}

	public PpeTurnoverAttach(String appNo, String ppeNo, String ppeName,
			String model, String unit, Integer qty, BigDecimal ppeAmt) {
		this.appNo = appNo;
		this.ppeNo = ppeNo;
		this.ppeName = ppeName;
		this.model = model;
		this.unit = unit;
		this.qty = qty;
		this.ppeAmt = ppeAmt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PTA_ID", unique = true, nullable = false)
	public Integer getPtaId() {
		return this.ptaId;
	}

	public void setPtaId(Integer ptaId) {
		this.ptaId = ptaId;
	}

	@Column(name = "APP_NO", length = 25)
	public String getAppNo() {
		return this.appNo;
	}

	public void setAppNo(String appNo) {
		this.appNo = appNo;
	}

	@Column(name = "PPE_NO", length = 20)
	public String getPpeNo() {
		return this.ppeNo;
	}

	public void setPpeNo(String ppeNo) {
		this.ppeNo = ppeNo;
	}

	@Column(name = "PPE_NAME", length = 50)
	public String getPpeName() {
		return this.ppeName;
	}

	public void setPpeName(String ppeName) {
		this.ppeName = ppeName;
	}

	@Column(name = "MODEL", length = 50)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Column(name = "UNIT", length = 10)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Column(name = "QTY")
	public Integer getQty() {
		return this.qty;
	}

	public void setQty(Integer qty) {
		this.qty = qty;
	}

	@Column(name = "PPE_AMT", precision = 10)
	public BigDecimal getPpeAmt() {
		return this.ppeAmt;
	}

	public void setPpeAmt(BigDecimal ppeAmt) {
		this.ppeAmt = ppeAmt;
	}

}
