package com.oasys.model;

// Generated 2015-9-24 9:33:54 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import org.springframework.format.annotation.DateTimeFormat;

import com.oasys.util.UniqueIdUtil;
import com.oasys.viewModel.WorkFlowTasksModel;

/**
 * TOaAdPpeTurnoverApp generated by hbm2java
 */
@Entity
@Table(name = "t_oa_ad_ppe_turnover_app", uniqueConstraints = @UniqueConstraint(columnNames = "APP_NO"))
public class PpeTurnoverApp implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer ptaId;
	private String appNo;
	private Integer applicantNo;
	private Integer appDept;
	private Date appDate;
	private String appStatus;
	private Date concedeDate;
	private String concedeReson;
	private String concedeAddr;
	private Integer takeoverDept;
	private Integer takeoverUser;
	private Integer ppeQty;
	private BigDecimal ppeTotalAmt;
	private String procStatus;
	private String remark;
	//申请人
	private String name;
	//申请部门
	private String appDeptName;
	//接收后使用人
	private String takeoverUserName;
	//接收部门
	private String takeoverDeptName;
	private String appDateBefore;//查询申请时间开始绑定字段
	private String appDateAfter;//查询申请时间结束绑定字段
	private String formKey;
	private String assistant;//指定的候选人
	@Transient
	public String getAssistant() {
		return assistant;
	}

	public void setAssistant(String assistant) {
		this.assistant = assistant;
	}
	@Transient
	public String getFormKey() {
		return formKey;
	}

	public void setFormKey(String formKey) {
		this.formKey = formKey;
	}

	@Transient
	public String getAppDateBefore() {
		return appDateBefore;
	}

	public void setAppDateBefore(String appDateBefore) {
		this.appDateBefore = appDateBefore;
	}
	@Transient
	public String getAppDateAfter() {
		return appDateAfter;
	}

	public void setAppDateAfter(String appDateAfter) {
		this.appDateAfter = appDateAfter;
	}
	/**
	 * task对象
	 */
	private WorkFlowTasksModel taskModel;
	@Transient
	public WorkFlowTasksModel getTaskModel() {
		return taskModel;
	}

	public void setTaskModel(WorkFlowTasksModel taskModel) {
		this.taskModel = taskModel;
	}

	@Transient
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	@Transient
	public String getAppDeptName() {
		return appDeptName;
	}

	public void setAppDeptName(String appDeptName) {
		this.appDeptName = appDeptName;
	}
	@Transient
	public String getTakeoverUserName() {
		return takeoverUserName;
	}

	public void setTakeoverUserName(String takeoverUserName) {
		this.takeoverUserName = takeoverUserName;
	}
	@Transient
	public String getTakeoverDeptName() {
		return takeoverDeptName;
	}

	public void setTakeoverDeptName(String takeoverDeptName) {
		this.takeoverDeptName = takeoverDeptName;
	}

	@Transient
	public String getTaskID() {
		return taskID;
	}

	public void setTaskID(String taskID) {
		this.taskID = taskID;
	}
	private String taskID;
	
	public PpeTurnoverApp() {
	}

	public PpeTurnoverApp(String appNo, Integer applicantNo,
			Integer appDept, Date appDate, String appStatus, Date concedeDate,
			String concedeReson, String concedeAddr, Integer takeoverDept,
			Integer takeoverUser, Integer ppeQty, BigDecimal ppeTotalAmt,
			String procStatus, String remark,String assistant) {
		this.appNo = appNo;
		this.applicantNo = applicantNo;
		this.appDept = appDept;
		this.appDate = appDate;
		this.appStatus = appStatus;
		this.concedeDate = concedeDate;
		this.concedeReson = concedeReson;
		this.concedeAddr = concedeAddr;
		this.takeoverDept = takeoverDept;
		this.takeoverUser = takeoverUser;
		this.ppeQty = ppeQty;
		this.ppeTotalAmt = ppeTotalAmt;
		this.procStatus = procStatus;
		this.remark = remark;
		this.assistant=assistant;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PTA_ID", unique = true, nullable = false)
	public Integer getPtaId() {
		return this.ptaId;
	}

	public void setPtaId(Integer ptaId) {
		this.ptaId = ptaId;
	}

	@Column(name = "APP_NO", unique = true, length = 25)
	public String getAppNo() {
		return this.appNo;
	}

	public void setAppNo(String appNo) {
		this.appNo = appNo;
	}

	@Column(name = "APPLICANT_NO")
	public Integer getApplicantNo() {
		return this.applicantNo;
	}

	public void setApplicantNo(Integer applicantNo) {
		this.applicantNo = applicantNo;
	}

	@Column(name = "APP_DEPT")
	public Integer getAppDept() {
		return this.appDept;
	}

	public void setAppDept(Integer appDept) {
		this.appDept = appDept;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "APP_DATE", length = 10)
	@DateTimeFormat(pattern="yyyy-MM-dd")
	public Date getAppDate() {
		return this.appDate;
	}

	public void setAppDate(Date appDate) {
		this.appDate = appDate;
	}

	@Column(name = "APP_STATUS", length = 100)
	public String getAppStatus() {
		return this.appStatus;
	}

	public void setAppStatus(String appStatus) {
		this.appStatus = appStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CONCEDE_DATE", length = 10)
	@DateTimeFormat(pattern="yyyy-MM-dd")
	public Date getConcedeDate() {
		return this.concedeDate;
	}

	public void setConcedeDate(Date concedeDate) {
		this.concedeDate = concedeDate;
	}

	@Column(name = "CONCEDE_RESON", length = 200)
	public String getConcedeReson() {
		return this.concedeReson;
	}

	public void setConcedeReson(String concedeReson) {
		this.concedeReson = concedeReson;
	}

	@Column(name = "CONCEDE_ADDR", length = 80)
	public String getConcedeAddr() {
		return this.concedeAddr;
	}

	public void setConcedeAddr(String concedeAddr) {
		this.concedeAddr = concedeAddr;
	}

	@Column(name = "TAKEOVER_DEPT")
	public Integer getTakeoverDept() {
		return this.takeoverDept;
	}

	public void setTakeoverDept(Integer takeoverDept) {
		this.takeoverDept = takeoverDept;
	}

	@Column(name = "TAKEOVER_USER")
	public Integer getTakeoverUser() {
		return this.takeoverUser;
	}

	public void setTakeoverUser(Integer takeoverUser) {
		this.takeoverUser = takeoverUser;
	}

	@Column(name = "PPE_QTY")
	public Integer getPpeQty() {
		return this.ppeQty;
	}

	public void setPpeQty(Integer ppeQty) {
		this.ppeQty = ppeQty;
	}

	@Column(name = "PPE_TOTAL_AMT", precision = 10)
	public BigDecimal getPpeTotalAmt() {
		return this.ppeTotalAmt;
	}

	public void setPpeTotalAmt(BigDecimal ppeTotalAmt) {
		this.ppeTotalAmt = ppeTotalAmt;
	}

	@Column(name = "PROC_STATUS", length = 1)
	public String getProcStatus() {
		return this.procStatus;
	}

	public void setProcStatus(String procStatus) {
		this.procStatus = procStatus;
	}

	@Column(name = "REMARK", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
	@Override
    public Object clone(){
    	try {
			return super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
    	return null;
    }
}
