package com.oasys.model;

// Generated 2015-10-10 14:43:11 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * TOaAdStampTurnoverAppAttach generated by hbm2java
 */
@Entity
@Table(name = "t_oa_ad_stamp_turnover_app_attach")
public class StampTurnoverAppAttach implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 6345333531607094585L;
	
	
	private Integer taaId;
	private String appNo;
	private String stampName;
	private String turnoverReson;
	private Character isGiveback;
	private String givebackDatetime;
	private String remark;
	
	private StampTurnoverApp stampTurnover;
	
	
	public StampTurnoverAppAttach() {
	}



	public StampTurnoverAppAttach(Integer taaId, String appNo,
			String stampName, String turnoverReson, Character isGiveback,
			String givebackDatetime, String remark, StampTurnoverApp stampTurnover) {
		super();
		this.taaId = taaId;
		this.appNo = appNo;
		this.stampName = stampName;
		this.turnoverReson = turnoverReson;
		this.isGiveback = isGiveback;
		this.givebackDatetime = givebackDatetime;
		this.remark = remark;
		this.stampTurnover = stampTurnover;
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "TAA_ID", unique = true, nullable = false)
	public Integer getTaaId() {
		return this.taaId;
	}

	public void setTaaId(Integer taaId) {
		this.taaId = taaId;
	}

	@Column(name = "APP_NO", length = 25)
	public String getAppNo() {
		return this.appNo;
	}

	public void setAppNo(String appNo) {
		this.appNo = appNo;
	}

	@Column(name = "STAMP_NAME", length = 80)
	public String getStampName() {
		return this.stampName;
	}

	public void setStampName(String stampName) {
		this.stampName = stampName;
	}

	@Column(name = "TURNOVER_RESON", length = 200)
	public String getTurnoverReson() {
		return this.turnoverReson;
	}

	public void setTurnoverReson(String turnoverReson) {
		this.turnoverReson = turnoverReson;
	}

	@Column(name = "IS_GIVEBACK", length = 1)
	public Character getIsGiveback() {
		return this.isGiveback;
	}

	public void setIsGiveback(Character isGiveback) {
		this.isGiveback = isGiveback;
	}

	@Column(name = "GIVEBACK_DATETIME", length = 19)
	public String getGivebackDatetime() {
		return this.givebackDatetime;
	}

	public void setGivebackDatetime(String givebackDatetime) {
		this.givebackDatetime = givebackDatetime;
	}

	@Column(name = "REMARK", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
	
	
	@Transient
	public StampTurnoverApp getStampTurnover() {
		return stampTurnover;
	}

	public void setStampTurnover(StampTurnoverApp stampTurnover) {
		this.stampTurnover = stampTurnover;
	}

}
