package com.oasys.model;

// Generated 2015-10-10 14:43:11 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import com.oasys.viewModel.WorkFlowTasksModel;

/**
 * TOaAdStampTurnoverApp generated by hbm2java
 */
@Entity
@Table(name = "t_oa_ad_stamp_turnover_app", uniqueConstraints = @UniqueConstraint(columnNames = "APP_NO"))
public class StampTurnoverApp implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = -8460528747501150469L;
	
	
	private Integer staId;
	private String appNo;
	private Integer applicantNo;
	private Integer appDept;
	private String appDate;
	private String appStatus;
	private String turnoverDate;
	private Integer receiverNo;
	private Integer receiverDept;
	private String receiverDate;
	private Integer superviserNo;
	private Integer superviserDept;
	private String superviserDate;
	private String remark;
	private String procStatus;
	
	private String appDateBefore;//查询申请时间开始绑定字段
	private String appDateAfter;//查询申请时间结束绑定字段
	private String orgName;//部门名称
	private String userName;//用户名称
	private String superviserOrgName;//监交人部门名称
	private String superviserUserName;//监交人用户名称
	private String receiverOrgName;//接收人部门名称
	private String receiverUserName;//接收人用户名称
	
	private String isHaveAttach;//是否存在附加项

	/** WorkFlow propertites */
	private WorkFlowTasksModel taskModel;//task对象
	private String result;//审批通过或驳回标识
	private String taskID;//任务taskID
	private String formKey;//跳转对应的受理页面JSP配置(在流程图的formKey中设置)
	private String assistant;//指定的候选人
	private String isSuccess;//是否通过标识
	private String resourcesName;//资源文件名称
	private String definitionKey;//流程标识Key

	
	public StampTurnoverApp(Integer staId, String appNo, Integer applicantNo,
			Integer appDept, String appDate, String appStatus, String turnoverDate,
			Integer receiverNo, Integer receiverDept, String receiverDate,
			Integer superviserNo, Integer superviserDept, String superviserDate,
			String remark, String appDateBefore, String appDateAfter,
			String orgName, String userName, WorkFlowTasksModel taskModel,
			String result, String taskID, String formKey, String assistant,
			String isSuccess, String resourcesName) {
		super();
		this.staId = staId;
		this.appNo = appNo;
		this.applicantNo = applicantNo;
		this.appDept = appDept;
		this.appDate = appDate;
		this.appStatus = appStatus;
		this.turnoverDate = turnoverDate;
		this.receiverNo = receiverNo;
		this.receiverDept = receiverDept;
		this.receiverDate = receiverDate;
		this.superviserNo = superviserNo;
		this.superviserDept = superviserDept;
		this.superviserDate = superviserDate;
		this.remark = remark;
		this.appDateBefore = appDateBefore;
		this.appDateAfter = appDateAfter;
		this.orgName = orgName;
		this.userName = userName;
		this.taskModel = taskModel;
		this.result = result;
		this.taskID = taskID;
		this.formKey = formKey;
		this.assistant = assistant;
		this.isSuccess = isSuccess;
		this.resourcesName = resourcesName;
	}
	
	

	public StampTurnoverApp() {
		super();
		// TODO Auto-generated constructor stub
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "STA_ID", unique = true, nullable = false)
	public Integer getStaId() {
		return this.staId;
	}

	public void setStaId(Integer staId) {
		this.staId = staId;
	}

	@Column(name = "APP_NO", unique = true, length = 25)
	public String getAppNo() {
		return this.appNo;
	}

	public void setAppNo(String appNo) {
		this.appNo = appNo;
	}

	@Column(name = "APPLICANT_NO")
	public Integer getApplicantNo() {
		return this.applicantNo;
	}

	public void setApplicantNo(Integer applicantNo) {
		this.applicantNo = applicantNo;
	}

	@Column(name = "APP_DEPT")
	public Integer getAppDept() {
		return this.appDept;
	}

	public void setAppDept(Integer appDept) {
		this.appDept = appDept;
	}

	@Column(name = "APP_DATE", length = 10)
	public String getAppDate() {
		return this.appDate;
	}

	public void setAppDate(String appDate) {
		this.appDate = appDate;
	}

	@Column(name = "APP_STATUS", length = 100)
	public String getAppStatus() {
		return this.appStatus;
	}

	public void setAppStatus(String appStatus) {
		this.appStatus = appStatus;
	}

	@Column(name = "TURNOVER_DATE", length = 10)
	public String getTurnoverDate() {
		return this.turnoverDate;
	}

	public void setTurnoverDate(String turnoverDate) {
		this.turnoverDate = turnoverDate;
	}

	@Column(name = "RECEIVER_NO")
	public Integer getReceiverNo() {
		return this.receiverNo;
	}

	public void setReceiverNo(Integer receiverNo) {
		this.receiverNo = receiverNo;
	}

	@Column(name = "RECEIVER_DEPT")
	public Integer getReceiverDept() {
		return this.receiverDept;
	}

	public void setReceiverDept(Integer receiverDept) {
		this.receiverDept = receiverDept;
	}

	@Column(name = "RECEIVER_DATE", length = 10)
	public String getReceiverDate() {
		return this.receiverDate;
	}

	public void setReceiverDate(String receiverDate) {
		this.receiverDate = receiverDate;
	}

	@Column(name = "SUPERVISER_NO")
	public Integer getSuperviserNo() {
		return this.superviserNo;
	}

	public void setSuperviserNo(Integer superviserNo) {
		this.superviserNo = superviserNo;
	}

	@Column(name = "SUPERVISER_DEPT")
	public Integer getSuperviserDept() {
		return this.superviserDept;
	}

	public void setSuperviserDept(Integer superviserDept) {
		this.superviserDept = superviserDept;
	}

	@Column(name = "SUPERVISER_DATE", length = 10)
	public String getSuperviserDate() {
		return this.superviserDate;
	}

	public void setSuperviserDate(String superviserDate) {
		this.superviserDate = superviserDate;
	}

	@Column(name = "REMARK", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
	
	
	@Column(name = "PROC_STATUS")
	public String getProcStatus() {
		return procStatus;
	}


	public void setProcStatus(String procStatus) {
		this.procStatus = procStatus;
	}
	
	
	
	@Transient
	public String getAppDateBefore() {
		return appDateBefore;
	}

	public void setAppDateBefore(String appDateBefore) {
		this.appDateBefore = appDateBefore;
	}
	@Transient
	public String getAppDateAfter() {
		return appDateAfter;
	}

	public void setAppDateAfter(String appDateAfter) {
		this.appDateAfter = appDateAfter;
	}
	@Transient
	public String getOrgName() {
		return orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}
	@Transient
	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Transient
	public WorkFlowTasksModel getTaskModel() {
		return taskModel;
	}
	public void setTaskModel(WorkFlowTasksModel taskModel) {
		this.taskModel = taskModel;
	}
	

	@Transient
	public String getResult() {
		return result;
	}

	public void setResult(String result) {
		this.result = result;
	}
	@Transient
	public String getTaskID() {
		return taskID;
	}

	public void setTaskID(String taskID) {
		this.taskID = taskID;
	}
	@Transient
	public String getFormKey() {
		return formKey;
	}

	public void setFormKey(String formKey) {
		this.formKey = formKey;
	}
	@Transient
	public String getAssistant() {
		return assistant;
	}

	public void setAssistant(String assistant) {
		this.assistant = assistant;
	}
	@Transient
	public String getIsSuccess() {
		return isSuccess;
	}

	public void setIsSuccess(String isSuccess) {
		this.isSuccess = isSuccess;
	}
	@Transient
	public String getResourcesName() {
		return resourcesName;
	}

	public void setResourcesName(String resourcesName) {
		this.resourcesName = resourcesName;
	}
	
	@Transient
	public String getSuperviserOrgName() {
		return superviserOrgName;
	}



	public void setSuperviserOrgName(String superviserOrgName) {
		this.superviserOrgName = superviserOrgName;
	}


	@Transient
	public String getSuperviserUserName() {
		return superviserUserName;
	}



	public void setSuperviserUserName(String superviserUserName) {
		this.superviserUserName = superviserUserName;
	}


	@Transient
	public String getReceiverOrgName() {
		return receiverOrgName;
	}



	public void setReceiverOrgName(String receiverOrgName) {
		this.receiverOrgName = receiverOrgName;
	}


	@Transient
	public String getReceiverUserName() {
		return receiverUserName;
	}



	public void setReceiverUserName(String receiverUserName) {
		this.receiverUserName = receiverUserName;
	}


	@Transient
	public String getIsHaveAttach() {
		return isHaveAttach;
	}



	public void setIsHaveAttach(String isHaveAttach) {
		this.isHaveAttach = isHaveAttach;
	}
	
	@Transient
	public String getDefinitionKey() {
		return definitionKey;
	}

	public void setDefinitionKey(String definitionKey) {
		this.definitionKey = definitionKey;
	}
	

}
