package com.oasys.model;

// Generated 2015-10-14 10:29:36 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * TOaAdUseReg generated by hbm2java
 * 固定资产领用表
 */
@Entity
@Table(name = "t_oa_ad_use_reg")
public class UseReg implements java.io.Serializable {

	private Integer urId;
	private Integer registrantNo;
	private Date regDatetime;
	private String ppeNo;
	private String ppeName;
	private Integer user;
	private Integer deptNo;
	private Integer useQty;
	private String useReson;
	private String remark;
	/**
	 * 登记人姓名
	 */
	private String registrantName;
	/**
	 * 部门名称
	 */
	private String deptNoName;
	/**
	 * 领用人姓名
	 */
	private String userName;
	/**
	 * 条件归还日期开始
	 */
	private String AppDateS;
	/**
	 * 条件归还日期结束
	 */
	private String AppDateE;

	public UseReg() {
	}

	
	
	public UseReg(Integer urId, Integer registrantNo, Date regDatetime,
			String ppeNo, String ppeName, Integer user, Integer deptNo,
			Integer useQty, String useReson, String remark,
			String registrantName, String deptNoName, String userName) {
		super();
		this.urId = urId;
		this.registrantNo = registrantNo;
		this.regDatetime = regDatetime;
		this.ppeNo = ppeNo;
		this.ppeName = ppeName;
		this.user = user;
		this.deptNo = deptNo;
		this.useQty = useQty;
		this.useReson = useReson;
		this.remark = remark;
		this.registrantName = registrantName;
		this.deptNoName = deptNoName;
		this.userName = userName;
	}


	@Transient
	public String getRegistrantName() {
		return registrantName;
	}

	public void setRegistrantName(String registrantName) {
		this.registrantName = registrantName;
	}
	@Transient
	public String getDeptNoName() {
		return deptNoName;
	}

	public void setDeptNoName(String deptNoName) {
		this.deptNoName = deptNoName;
	}
	@Transient
	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}
	@Transient
	public String getAppDateS() {
		return AppDateS;
	}
	
	public void setAppDateS(String appDateS) {
		AppDateS = appDateS;
	}
	@Transient
	public String getAppDateE() {
		return AppDateE;
	}



	public void setAppDateE(String appDateE) {
		AppDateE = appDateE;
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "UR_ID", unique = true, nullable = false)
	public Integer getUrId() {
		return this.urId;
	}

	public void setUrId(Integer urId) {
		this.urId = urId;
	}

	@Column(name = "REGISTRANT_NO")
	public Integer getRegistrantNo() {
		return this.registrantNo;
	}

	public void setRegistrantNo(Integer registrantNo) {
		this.registrantNo = registrantNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REG_DATETIME", length = 19)
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	public Date getRegDatetime() {
		return this.regDatetime;
	}

	public void setRegDatetime(Date regDatetime) {
		this.regDatetime = regDatetime;
	}

	@Column(name = "PPE_NO", length = 20)
	public String getPpeNo() {
		return this.ppeNo;
	}

	public void setPpeNo(String ppeNo) {
		this.ppeNo = ppeNo;
	}

	@Column(name = "PPE_NAME", length = 50)
	public String getPpeName() {
		return this.ppeName;
	}

	public void setPpeName(String ppeName) {
		this.ppeName = ppeName;
	}

	@Column(name = "USER")
	public Integer getUser() {
		return this.user;
	}

	public void setUser(Integer user) {
		this.user = user;
	}

	@Column(name = "DEPT_NO")
	public Integer getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(Integer deptNo) {
		this.deptNo = deptNo;
	}

	@Column(name = "USE_QTY")
	public Integer getUseQty() {
		return this.useQty;
	}

	public void setUseQty(Integer useQty) {
		this.useQty = useQty;
	}

	@Column(name = "USE_RESON", length = 200)
	public String getUseReson() {
		return this.useReson;
	}

	public void setUseReson(String useReson) {
		this.useReson = useReson;
	}

	@Column(name = "REMARK", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
